### ISSUE TITLE
Additional unwanted hex characters being added to the URL

### ISSUE THREAD

**Issue by gareth41** [abeade/browser-websocket-client#14]
I wrote a websocket server in C and have been using this Chrome extension for testing it.

There appears to be a few additional characters being added to the URL, see the Wireshark capture below.  The additional characters are always 0xE2 0x80 0xAD.

The GET URL i'm using below should read as "/87EB/‭500" not "/87EB/‭%E2%80%AD500"

If I use a different variation of the GET URL, the random characters disappear.

![image](https://user-images.githubusercontent.com/12389533/77309076-df5e2b00-6d60-11ea-980a-30747098b4c3.png)

**Comment by abeade** [comment]
Hi @gareth41 

I think the characters you're seeing are the UTF-8 [left to right override](https://www.fileformat.info/info/unicode/char/202d/index.htm):
U+202D | ‭ | e2 80 ad | LEFT-TO-RIGHT OVERRIDE

The plugin is not doing any treatment of the characters in the URL, it is directly passed to the WebSocket object:
https://github.com/abeade/browser-websocket-client/blob/06b15c787579180b60a32b54dc161d11fd284013/src/main/index.js#L1035-L1040

I belive the URL enconding is done by the WebSocket object, in such case, there is nothing do from my side.
